### ISSUE TITLE
Enable Logging?

### ISSUE THREAD

**Issue by dominikraff** [joelbutcher/laravel-googleads#2]
How can i enable logging the call queries?

I tried this, but there is no logging of the queries?

`  $l = new MyCustomLogger();
                $this->googleAds = new GoogleAds($this->clientId,$this->clientSecret, $this->developerToken, SupportedVersions::VERSION_10, 'rest', $l, 'debug');`

**Comment by joelbutcher** [comment]
I'm not sure this is a bug with this package. If you've passed a correct instance of the monolog logger interface, you should be seeing request logs...

I'll see if I can replicate this issue myself
