### ISSUE TITLE
V13 deprecated

### ISSUE THREAD

**Issue by dominikraff** [joelbutcher/laravel-googleads#8]
Hello.
can you change to v15 in your GoogleAds.php File?
public function __construct(
        private string $clientId,
        private string $clientSecret,
        private string $developerToken,
        private int $sdkVersion = SupportedVersions::VERSION_13,
        private string $transportProtocol = 'rest',
        private ?LoggerInterface $logger = null,
        private string $logLevel = 'INFO'
    ) {
    
    Regards, DOminik

**Comment by joelbutcher** [comment]
Wrong repo – [joelbutcher/googleads](https://github.com/joelbutcher/googleads) is the one you're looking for :)

**Comment by dominikraff** [comment]
Sorry, will you change this there?

 

 

Von: Joel Butcher ***@***.***> 
Gesendet: Freitag, 9. Februar 2024 10:53
An: joelbutcher/laravel-googleads ***@***.***>
Cc: dominikraff ***@***.***>; Author ***@***.***>
Betreff: Re: [joelbutcher/laravel-googleads] V13 deprecated (Issue #8)

 

Wrong repo – joelbutcher/googleads <https://github.com/joelbutcher/googleads>  is the one you're looking for :)

**Comment by joelbutcher** [comment]
Please update your composer to use `v7.0.0` of this package, which should use `v8.0.0` of the base Google Ads SDK
